server:
  port: 8082

spring:
  application:
    name: activity-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fitnessActivity
      username: fitsync
      password: fitsyncpassword
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: fitsync
    password: fitsyncpassword

# Actuator Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

#RabbitMQ Configuration
rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking


  #Spring Cloud Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true