server:
  port: 8082

spring:
  application:
    name: activity-service
  config:
    import: common.yml
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fitnessActivity
      username: fitsync
      password: fitsyncpassword
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: fitsync
    password: fitsyncpassword

# RabbitMQ Configuration
rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking