server:
  port: 8083

spring:
  application:
    name: ai-service
  config:
    import: common.yml
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fitnessRecommendations
      username: fitsync
      password: fitsyncpassword
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: fitsync
    password: fitsyncpassword

# RabbitMQ Configuration
rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
  listener:
    concurrency: 5
    max-concurrency: 10
    prefetch: 250

# Google Gemini Configuration
gemini:
  api:
    url: https://generativelanguage.googleapis.com
    key: ${GEMINI_API_KEY}