server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: common.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/fitsyncai_user
    username: fitsyncai
    password: fitsyncaipassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    table: flyway_schema_history