server:
  port: 8761

spring:
  application:
    name: eureka

# Eureka Configuration
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# Actuator Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true